=> [[32m#<Festival:0x00000000c8df48[0m
  @description[32m=[0m
   [31m[1;31m"[0m[31mHome to some of Australia’s most prominent wine-growing regions, wide swaths of the Outback and such biodiverse destinations as Kangaroo Island and the Limestone Coast, it would feasibly take months (or even years) to explore the reaches of South Australia‘s gastronomy and viticulture—not to mention its many scenic regions.[1;35m\n[0m[31m[1;35m\n[0m[31mThankfully, Tasting Australia condenses many of the state’s food and wine highlights into a robust 10-day program of more than 140 events—farm tours, wine, beer, and spirits tastings and masterclasses, leisurely chef-driven lunches and dinners included. Festival highlights include the Glasshouse Kitchen in the capital city of Adelaide, where lauded Australian chefs and international culinary stars team up for some memorable meals, and Tasting Australia Airlines, which transports visitors to some of the state’s more remote culinary destinations on all-inclusive full-day tours.[1;31m"[0m[31m[0m,
  @location[32m=[0m[31m[1;31m"[0m[31mSouth Australia[1;31m"[0m[31m[0m,
  @name[32m=[0m[31m[1;31m"[0m[31mTasting Australia[1;31m"[0m[31m[0m[32m>[0m,
 [32m#<Festival:0x0000000103f808[0m
  @description[32m=[0m
   [31m[1;31m"[0m[31mAt its inaugural event in May, the Venice Food & Wine Festival lined up American and Italian culinary luminaries with more than a few Michelin stars (and James Beard awards) for its four-day showcase at the JW Marriott Venice Resort & Spa, which is located on its own private island in Venice, the Isola delle Rose. On the agenda: chef-led demos, cooking academies, wine tastings, cocktail workshops and a few fabulous dinners, of course. As a bonus, the opening party and concert finale are complimentary to all guests staying at the resort over the weekend.[1;31m"[0m[31m[0m,
  @location[32m=[0m[31m[1;31m"[0m[31mVenice, Italy[1;31m"[0m[31m[0m,
  @name[32m=[0m[31m[1;31m"[0m[31mVenice Food & Wine Festival[1;31m"[0m[31m[0m[32m>[0m,
 [32m#<Festival:0x00000000c397b8[0m
  @description[32m=[0m
   [31m[1;31m"[0m[31mThe roster of celebrity chefs who head for Las Vegas every May for Vegas Uncork’d—Sin City’s extravagant, four-day epicurean feast and drink fest—is impressive, to say the least. Gordon Ramsay, Bobby Flay, Giada De Laurentiis, Masaharu Morimoto and Nobu Matsuhisa are all Vegas Uncork’d regulars and each edition brings a host of new and notable events and culinary all-star talent, too.[1;35m\n[0m[31m[1;35m\n[0m[31mThe festival’s busy agenda features dine-around showcases, master series with star chefs, brunches, poolside parties and more, but the weekend’s signature event is The Grand Tasting at Caesars Palace, which can accommodate upwards of 2,500 revelers. More than 50 chef-helmed stations—and twice as many wine and cocktail stops—ensures that no attendee will depart this annual desert bacchanal either hungry or thirsty.[1;31m"[0m[31m[0m,
  @location[32m=[0m[31m[1;31m"[0m[31mLas Vegas, Nevada[1;31m"[0m[31m[0m,
  @name[32m=[0m[31m[1;31m"[0m[31mVegas Uncork’d[1;31m"[0m[31m[0m[32m>[0m,
 [32m#<Festival:0x0000000179b958[0m
  @description[32m=[0m
   [31m[1;31m"[0m[31mA relative newcomer to the food festival scene, Food Zurich continues to grow and morph with each iteration and its latest May-June edition, which ran for a total of 11 days, was no exception. In just a few years, the festival has grown to more than 150 cooking workshops, events and tasting sessions connecting food producers and chefs from Zurich and beyond with local food enthusiasts.[1;35m\n[0m[31m[1;35m\n[0m[31mBespoke dinners and tastings are held at restaurants throughout the city as well as at more unusual settings, too—think museums, castles, and other countryside locations. The Street Food Festival, one of Food Zurich’s most popular events, has around 70 vendors offering global fare and plenty of Swiss classics—no doubt you’ll be able to get your pretzel and bratwurst fix, and then some.[1;31m"[0m[31m[0m,
  @location[32m=[0m[31m[1;31m"[0m[31mZurich, Switzerland[1;31m"[0m[31m[0m,
  @name[32m=[0m[31m[1;31m"[0m[31mFood Zurich[1;31m"[0m[31m[0m[32m>[0m]
